# Uses debian multiarch to build librespot for armv7.
FROM buildpack-deps:buster

RUN apt-get update \
 && apt-get install -yq \
    g++-arm-linux-gnueabihf \
    libc6-dev-armhf-cross

ENV CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- --default-toolchain stable -y \
 && rustup target add armv7-unknown-linux-gnueabihf

RUN dpkg --add-architecture armhf \
 && apt-get update \
 && apt-get install -yq \
    libavahi-compat-libdnssd-dev:armhf \
    libasound2-dev:armhf \
    pkg-config:armhf

ENV PKG_CONFIG_PATH_arm-unknown-linux-gnueabihf=/usr/lib/arm-linux-gnueabihf/pkgconfig \
    PKG_CONFIG_ALLOW_CROSS=1

RUN mkdir -p /opt/src/librespot \
 && curl -Lfq "https://github.com/librespot-org/librespot/archive/refs/tags/v0.1.6.tar.gz" | tar -C /opt/src/librespot --strip-components 1 -xzvf - \
 && cd /opt/src/librespot \
 && mkdir -p .cargo \
 && printf '[target.armv7-unknown-linux-gnueabihf]\nlinker = "arm-linux-gnueabihf-gcc"' >> .cargo/config \
 && cargo build --target=armv7-unknown-linux-gnueabihf --release --no-default-features --features alsa-backend,with-dns-sd