#!/usr/bin/env bash
set -eo pipefail

# script to control turning amp on and off
cat <<-'EOF' > /usr/local/bin/amp
#!/usr/bin/env bash
set -eo pipefail

GPIO=23

if [ ! -d /sys/class/gpio/gpio${GPIO} ] ; then
  echo "$GPIO" > /sys/class/gpio/export
  echo "out" > /sys/class/gpio/gpio${GPIO}/direction
fi

case "$1" in
  "on")
    if grep -q '^0$' /sys/class/gpio/gpio${GPIO}/value ; then
      echo "1" > /sys/class/gpio/gpio${GPIO}/value
    fi
  ;;
  "off")
    echo "0" > /sys/class/gpio/gpio${GPIO}/value
  ;;
  "status")
    if grep -q 1 /sys/class/gpio/gpio${GPIO}/value ; then
      echo "on"
    else
      echo "off"
    fi
  ;;
  *)
    echo "unknown option. expecting exactly one argument of 'on' or 'off'" >&2
    exit 1
  ;;
esac
EOF
chmod a+x /usr/local/bin/amp

# expose serial port via http service
cat <<-'EOF' > /etc/systemd/system/amp.service
[Unit]
Description=Expose amp Serial control over HTTP
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/local/bin/amp-httpd-rpi
Restart=always
RestartSec=2

[Install]
WantedBy=default.target
EOF

systemctl enable amp.service
