#!/usr/bin/env bash
set -eo pipefail

# script to control turning amp on and off
cat <<-'EOF' > /usr/local/bin/amp
#!/usr/bin/env bash
set -eo pipefail

GPIO=23

if [ ! -d /sys/class/gpio/gpio${GPIO} ] ; then
  echo "$GPIO" > /sys/class/gpio/export
  echo "out" > /sys/class/gpio/gpio${GPIO}/direction
fi

case "$1" in
  "on")
    if grep -q '^0$' /sys/class/gpio/gpio${GPIO}/value ; then
      echo "1" > /sys/class/gpio/gpio${GPIO}/value
    fi
  ;;
  "off")
    echo "0" > /sys/class/gpio/gpio${GPIO}/value
  ;;
  "status")
    if grep -q 1 /sys/class/gpio/gpio${GPIO}/value ; then
      echo "on"
    else
      echo "off"
    fi
  ;;
  *)
    echo "unknown option. expecting exactly one argument of 'on' or 'off'" >&2
    exit 1
  ;;
esac
EOF
chmod a+x /usr/local/bin/amp

# expose serial port via http service
cat <<-'EOF' > /etc/systemd/system/amp.service
[Unit]
Description=Expose amp Serial control over HTTP
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/local/bin/amp-httpd-rpi
Restart=always
RestartSec=2

[Install]
WantedBy=default.target
EOF

systemctl enable amp.service

# turn off amp after 15 min of idle time
cat <<-'EOF' > /usr/local/bin/amp-sleep
#!/usr/bin/env bash
set -eo pipefail

if [ /var/log/spotify-last-event.log -nt /var/log/amp-sleep.log ] ; then
  if grep -qE '^(paused|stopped)$' /var/log/spotify-last-event.log; then
    age=$(expr $(date +%s) - $(date -r /var/log/spotify-last-event.log +%s))
    if [ $age -gt 900 ] ; then
      echo "turning amp off"
      /usr/local/bin/amp off
      touch /var/log/amp-sleep.log
    fi
  fi
fi
EOF
chmod a+x /usr/local/bin/amp-sleep

cat <<-'EOF' > /etc/systemd/system/amp-sleep.service
[Unit]
Description=Check if amp should sleep
Wants=amp-sleep.timer

[Service]
Type=oneshot
ExecStart=/usr/local/bin/amp-sleep

[Install]
WantedBy=default.target
EOF

cat <<-'EOF' > /etc/systemd/system/amp-sleep.timer
[Unit]
Description=Check if amp should sleep
Requires=amp-sleep.service

[Timer]
OnCalendar=minutely

[Install]
WantedBy=timers.target
EOF

systemctl enable amp-sleep.service
systemctl enable amp-sleep.timer