#!/usr/bin/env bash
set -eo pipefail

cat <<-EOF >> /etc/wpa_supplicant/wpa_supplicant.conf
country=US

network={
    ssid="${WIFI_SSID}"
    scan_ssid=1
    key_mgmt=WPA-PSK
    psk="${WIFI_PASSWORD}"
}
EOF

mkdir -p /var/lib/systemd/rfkill/
echo 0 > /var/lib/systemd/rfkill/platform-fe300000.mmcnr:wlan

echo "pi-music" > /etc/hostname
echo "127.0.0.1 pi-music" >> /etc/hosts