#!/usr/bin/env bash
set -eo pipefail

chmod a+x /usr/local/bin/librespot

DEBIAN_FRONTEND=noninteractive apt-get install -yq libavahi-compat-libdnssd-dev avahi-daemon

cat <<-'EOF' > /etc/systemd/system/spotify.service
[Unit]
Description=A spotify playing daemon
Documentation=https://github.com/librespot-org/librespot
Wants=sound.target network-online.target
Requires=avahi-daemon.service
After=sound.target network-online.target avahi-daemon.service

[Service]
ExecStart=/usr/local/bin/librespot \
          --name multizone \
          --device-type speaker \
          --bitrate 320 \
          --volume-ctrl fixed \
          --initial-volume 100 \
          --enable-volume-normalisation \
          --normalisation-pregain 0 \
          --normalisation-gain-type track \
          --autoplay \
          --onevent /usr/local/bin/spotify-event-handler
Restart=always
RestartSec=2

[Install]
WantedBy=default.target
EOF
systemctl enable spotify.service

# control the amp on spotify events
# list of events: https://github.com/librespot-org/librespot/blob/v0.1.6/src/player_event_handler.rs
cat <<-'EOF' > /usr/local/bin/spotify-event-handler
#!/usr/bin/env bash
set -eo pipefail

echo "$PLAYER_EVENT" > /var/run/spotify-last-event
case $PLAYER_EVENT in
  started|playing|changed|preloading)
    curl -f -X PUT -d power=1 http://localhost:8080/power
    ;;
esac
EOF
chmod a+x /usr/local/bin/spotify-event-handler
