#!/usr/bin/env bash
set -eo pipefail

# default password is not set in bullseye
echo pi:raspberry | chpasswd

systemctl enable ssh.service
echo "PasswordAuthentication no" >> /etc/ssh/sshd_config

mkdir -p ~pi/.ssh
cat /tmp/id_rsa.pub >> ~pi/.ssh/authorized_keys
chown -R pi:pi ~pi/.ssh